### ISSUE TITLE
iPad Support

### ISSUE THREAD

**Issue by petermbenjamin** [thepracticaldev/DEV-ios#100]
**Describe the bug**
The app doesn't seem to be optimized for iPad (at least the 11" model for me)

**To Reproduce**
1. Rotate iPad to landscape mode
1. Launch the app.

**Expected behavior**
The app should rotate to landscape mode and scale to the full resolution of the screen.

**Screenshots**
![img_0007](https://user-images.githubusercontent.com/6811830/48993722-4f6c8a80-f0f4-11e8-8c24-9bd8337eb37f.png)

**Device Info (please complete the following information):**
 - Device: 2018 iPad 11"
 - OS: iOS 12.1
 - Version 12

**Comment by petermbenjamin** [comment]
Worth noting, workaround is to use the web app.

**Comment by benhalpern** [comment]
Yes. Forewent iPad on initial release to have less to think about. Our overall traffic on iPhone vs iPad is pretty low so it seemed fine, though this is certainly a strong minority to support given the site is about _reading_.

There isn't much to supporting iPad in a basic at this point besides getting the constraints to line up. I know @Gary-Ash is heavily in favor of this as well.

Happy to accept PRs that do the basic stuff. 🙂

**Comment by thesohelshaikh** [comment]
iPads are great for reading and it would be great if there were direct support. I like to stay away from my phone to avoid distractions while reading. 

I’ll be waiting for this one!

**Comment by StriderHND** [comment]
I'll take a look into this @benhalpern

**Comment by StriderHND** [comment]
Hello I've been doing some tests for the iPad support for the dev App. 

Here are some screenshoots
![img_36135b069631-1](https://user-images.githubusercontent.com/430328/49606588-682d3980-f959-11e8-9b68-09f984bbbf62.jpeg)

![img_36f886530e1b-1](https://user-images.githubusercontent.com/430328/49606594-6a8f9380-f959-11e8-9086-0b7ad00a4886.jpeg)

I need to do some testing but I don't feel very fluid the transition of orientation of the web view so I'll look how improve this.

**Comment by StriderHND** [comment]
@benhalpern @maestromac please close this issue.

**Comment by maestromac** [comment]
👌 

Resolved with #112
