### ISSUE TITLE
Add haptic feedback

### ISSUE THREAD

**Issue by benhalpern** [thepracticaldev/DEV-ios#102]
The app should be able to respond with haptic feedback (vibrate, etc.) where appropriate within the user experience.

But the app shouldn't be responsible for the business logic. It should simply receive instructions to vibrate or respond to any other cue.

I believe we can use `webkit.messageHandlers` for this on the web app side or some other approach.

Importantly, we have to define whatever the approach is and implement it. Once we define and ship this on the app side of things we can start sending signals via the web app.

**Comment by StriderHND** [comment]
@benhalpern I'll look at this feature! so we can start to define how should behave to get implemented.

**Comment by benhalpern** [comment]
Awesome @StriderHND

**Comment by StriderHND** [comment]
The haptic feedback initially will be reaction button clicks and the pull-to-refresh functionality or any other event trigger by the web app right ?

**Comment by benhalpern** [comment]
Correct. As to be triggered by code in the web app that the `wkwebview` can hear. The iOS side should define what exactly that protocol will be.

**Comment by chickdan** [comment]
Reminder to close since #110 has been merged.

**Comment by maestromac** [comment]
Thanks @chickdan 

Closing
