### ISSUE TITLE
Network connectivity bar too sensitive

### ISSUE THREAD

**Issue by benhalpern** [thepracticaldev/DEV-ios#114]
The bar sometimes shows up when I first open the app as not connected. It's been fairly consistently showing up a bit too often even if it's possibly technically correct.

The one case it shows up too much in general is right when the app is launched. I don't think we need that status update.

It works appropriately when network connection changes.

A nice to have is having it show up as a result of page navigation attempts within the app.

**Comment by StriderHND** [comment]
I'll take a look into this and see what could be causing the problem

**Comment by chickdan** [comment]
Even throttling my network connection I am unable to reproduce this behavior. 

That said, it shouldn't be too difficult to change to where it only makes the check on page navigation and I can make the changes after work, if desired.

**Comment by StriderHND** [comment]
> Even throttling my network connection I am unable to reproduce this behavior.
> 
> That said, it shouldn't be too difficult to change to where it only makes the check on page navigation and I can make the changes after work, if desired.

I've already something for it, haven't done the PR yet.

**Comment by StriderHND** [comment]
Sorry for the delay on this I'll be sending my PR for review today.

**Comment by benhalpern** [comment]
No worries, great work @StriderHND

**Comment by StriderHND** [comment]
Hello @benhalpern did you review the changes? #121
