### ISSUE TITLE
Loading icon

### ISSUE THREAD

**Issue by benhalpern** [thepracticaldev/DEV-ios#115]
When you first open the app, we should have a loading icon until the page is fetched.

This should happen when the app is first launched, and also when opening the app from a notification.

I think the default spinner is good for now, but perhaps we could replace it with a custom animation in the future.

**Comment by StriderHND** [comment]
I'll look this @benhalpern, if there is a moment we move to a custom animation we could use this [library](https://github.com/airbnb/lottie-ios) to make the custom animations. is loading spinner should only show at first open and from a notification, not every time that the app makes a request.
