### ISSUE TITLE
Double click notifications tab should refresh

### ISSUE THREAD

**Issue by benhalpern** [thepracticaldev/DEV-ios#12]
When a tab is clicked while it is the active tab, it should reload that tab. Basically this is the "refresh/go home" functionality users expect.

This behavior is defined in `AppDelegate` right now, and the last PR broke this. Which is fine, let's just get this behavior working properly.

I originally put this in AppDelegate and found some kind of way to get it working. Would definitely welcome better approaches or moving this to a better place.

## Definition of done

Once the intended behavior works, I'm satisfied. If it also improves the code, all the better.

**Comment by JacobBoyd** [comment]
We could create a 'RootTabBarViewController' use it as the delegate and have the root tab VCs subclass it.  I'd optional bind the tabBar in viewDidLoad, and create a refresh method.  I noticed the DevWebViewController is currently only used on the NotificationVC, maybe we could merge the two?

**Comment by benhalpern** [comment]
@JacobBoyd I sort of have to hedge everything I say against still being pretty newbie in iOS, but what you're describing makes sense to me. I'll have a better grip if I can review a PR. And if it leads to the expected behavior without hiccup, I'd love to merge it!

The overall code footprint is pretty small altogether for the app so far, so I'm not too concerned with imperfect architecture as long as the code stays readable. So if we move things around a bunch while we figure it out, it's alright with me!

**Comment by JacobBoyd** [comment]
Awesome! I have some prelim. changes I made this morning posted on my fork, but thought of additional changes I want to make before posting the PR!

**Comment by benhalpern** [comment]
Can't wait @JacobBoyd!
