### ISSUE TITLE
Bottom nav color/border problem

### ISSUE THREAD

**Issue by benhalpern** [thepracticaldev/DEV-ios#122]
We finally shipped this change to the app store, which was nice: https://github.com/thepracticaldev/DEV-ios/issues/100

But I noticed one issue I missed on the initial review.

Previously the bottom toolbar had a color that matched the "article page" bottom toolbar from the web: the tan color.

And the top border for the native nav bar turned "on" and "off" depending on the view.

This functionality was in `modifyShellDesign()` which checked for page content and called either `addShellShadow()` and `removeShellShadow()`.

The `modifyShellDesign()` is being called, but the overall functionality is not working due to modifications in the toolbar's style.

Let me know if this makes sense.

The appropriate behavior should be:

- When on article show view, there should be no top border on the native toolbar and the background color should match the tan color on the web.
- When not on the article show view, there should be a subtle top border on this toolbar.

**Comment by StriderHND** [comment]
Thanks @benhalpern.

This is posible to do with the existing `UINavigationBar` and `UIToolBar`.

I'll make some refectory to the mentioned functions to work as expected.

**Comment by benhalpern** [comment]
I played around with it and found some possible solutions, but I think it's better in your hands. Let me know if you need any clarifications. If you revert to before that previous commit you should see what I mean if there is any lack of clarity.

**Comment by StriderHND** [comment]
> I played around with it and found some possible solutions, but I think it's better in your hands. Let me know if you need any clarifications. If you revert to before that previous commit you should see what I mean if there is any lack of clarity.

I'll do the revert to see the changes. if I've questions I'll let you know.

**Comment by StriderHND** [comment]
Please review PR #123
