### ISSUE TITLE
Difficult to See Cursor for Text Input

### ISSUE THREAD

**Issue by michael-tharrington** [thepracticaldev/DEV-ios#140]
We recently received this feedback about the color of the cursor chosen for text input in the iOS app:

"Dev.to is great, thanks!
I didn’t know there was an iOS app- so I got it the other day. For all the text input the cursor is white instead of black. It’s impossible to see!

Cheers!

Sent from my iPhone"

**Comment by 1dancook** [comment]
I usually have my screen brightness quite low so I couldn't make it out. Here's a picture to hopefully provide better feedback. It's sort of transparent yellow, not white! But it makes it quite hard type on iOS.

![IMG_5812](https://user-images.githubusercontent.com/12954427/56941525-f516a080-6b4f-11e9-9017-6163ea86c757.PNG)

**Comment by petermbenjamin** [comment]
Somewhat related, but not about text input fields.

The text selection in the iOS app is same color (light/faint yellow):
![A70C9BC2-7084-42C3-8B9C-D45B869B7A18](https://user-images.githubusercontent.com/6811830/57415812-5ffc5300-71b2-11e9-8ae7-940106022233.jpeg)

**Comment by AbuSalem0324** [comment]
Same issue, really hard to see where is my cursor.

**Comment by 1dancook** [comment]
Can be closed as most recent app update fixed the issue. (2019-05-15)
