### ISSUE TITLE
Have a PR Template

### ISSUE THREAD

**Issue by obitodarky** [thepracticaldev/DEV-ios#174]
**Is your feature request related to a problem? Please describe.**
This repository does not seem to have a PR template. Most of the good repositories follow a PR template to make it easier for contributors and maintainers to publish and view Pull Requests

**Describe the solution you'd like**
I would suggest a good PR template be created for this repository. Preferably ones that suggest contributors add screenshots for UI changes if possible and describe their change in detail.

**Comment by obitodarky** [comment]
@benhalpern I would like to work on this issue.

**Comment by jessleenyc** [comment]
@obitodarky want to take a look at the PR template we have for the web app and update it to be applicable to iOS? 

https://github.com/thepracticaldev/dev.to/blob/master/.github/PULL_REQUEST_TEMPLATE.md

**Comment by obitodarky** [comment]
Fixed in #177
