### ISSUE TITLE
Add Code of Conduct

### ISSUE THREAD

**Issue by obitodarky** [thepracticaldev/DEV-ios#178]
**Is your feature request related to a problem? Please describe.**
This repository does not have a COC which is necessary for a good repository to have.

**Describe the solution you'd like**
We could have the Code Of Conduct from the [Web App Repo](https://github.com/thepracticaldev/dev.to/blob/master/CODE_OF_CONDUCT.md)

**Comment by jessleenyc** [comment]
Completely agree. We can use the same one from the web app.

**Comment by jessleenyc** [comment]
Oh, i see you already submitted a pr. Thanks!
