### ISSUE TITLE
App crashes when DarkTheme enabled on iOS 13

### ISSUE THREAD

**Issue by MichalRogowski** [thepracticaldev/DEV-ios#180]
**Describe the bug**
App crashes when DarkTheme enabled on iOS 13, 
`*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'App called -statusBar or -statusBarWindow on UIApplication: this code must be changed as there's no longer a status bar or status bar window. Use the statusBarManager object on the window scene instead.'
`
**To Reproduce**
1. Install app from Xcode 11.0+
2. Go to Sign in screen
3. Sign in to account with dark theme enabled
4. App crashes

**Expected behavior**
App should not crash

**Smartphone (please complete the following information):**
 - Device: iPhone 11
 - OS: iOS 13.1
 - Version 1.2.1 Build 13

**Additional context**
Crash is caused by this line
            guard let statusBarView = UIApplication.`shared.value(forKeyPath: "statusBarWindow.statusBar") as? UIView else {`

**Comment by maestromac** [comment]
Resolved with https://github.com/thepracticaldev/DEV-ios/pull/181
