### ISSUE TITLE
Missing icon and app

### ISSUE THREAD

**Issue by quostta** [thepracticaldev/DEV-ios#194]
**Describe the bug**
Whenever you do a hard touch (3D touch) on any app on an iOS device, the DEV app icon is reset to a placeholder. And tapping on the icon doesn't do anything. The app is basically non-existent until another 3D touch is performed. DEV is the only app this happens to.

**To Reproduce**
1. Hard touch (3D touch) on any app
2. Watch the DEV app icon and name disappear
3. There is still a placeholder for the app. App is inactive.
4. Trigger another hard touch
5. Watch the DEV app icon and name reappear. App is active again.

**Expected behavior**
Icon and name shouldn't disappear. App should be active and working.

**Screenshots**
![bug](https://user-images.githubusercontent.com/55330600/70450100-c0b17e00-1a68-11ea-9d7b-df1840913b4c.gif)

**Smartphone:**
 - Device: iPhone 6s Plus
 - OS: iOS
 - Version 13.2.3

**Comment by cuoong** [comment]
I'll fix that.

**Comment by jessleenyc** [comment]
@cuoong please go for it!

**Comment by cuoong** [comment]
@quostta Could you let me know the bug occurred on the simulator or real device?
I've tried to reproduce the bug but the app still works fine on the simulator.

**Comment by quostta** [comment]
Real device. And I believe it's fixed now.
