### ISSUE TITLE
Fix colors in safe area

### ISSUE THREAD

**Issue by benhalpern** [thepracticaldev/DEV-ios#205]
Currently the colors in the safe area reflect the user's OS-level preferences, which may conflict if they have the light version of the app in their DEV settings.

Meaning if you have dark settings but use the default DEV theme, you'll see white-on-tan colors, which is a problem.

We should either fix this so that the colors or not mismatched _or_ we make the theme match the user's choice. Since our settings are typically driven by the web, we would need to decide how we want to go about this in terms of communicating to the user and allowing for changing of should they want to.

Twitter has a "use device settings" boolean option which determines the answer here.

**Comment by justinhhorner** [comment]
@benhalpern I'd like to work on this issue 🙂

**Comment by fdoxyz** [comment]
Hey @justinhhorner, if you feel comfortable sending in a PR I would say go ahead! Either way if you need some help let me know and I'll try to help 👍🏼

**Comment by justinhhorner** [comment]
Thank you, @fdoxyz!

I'll submit a PR later soon (hopefully later today). I'd appreciate any feedback you have on my approach to resolve the defect, as this will be my first time contributing to the project.
