### ISSUE TITLE
Maintain audio playback speed if paused/played

### ISSUE THREAD

**Issue by benhalpern** [thepracticaldev/DEV-ios#216]
If I am listening on 1.5x speed and I click pause and then click play again, I go back to 1x speed audio.

**Comment by benhalpern** [comment]
@fdoxyz I was curious about this so I gave it a whirl. Not sure if perfect implementation but I think it works.

**Comment by fdoxyz** [comment]
Should be fairly easy to fix. Hoping to send in a PR for this today.
