### ISSUE TITLE
White Lines on Top and Bottom of App in Dark Mode

### ISSUE THREAD

**Issue by xarielx** [thepracticaldev/DEV-ios#230]
Describe the bug
When using the app on iOS in dark mode, even though my phone is also on dark mode, the top and bottom "navbars"  are of white color. Ruining the purpose of dark mode or theme. 

Screen Shot attached: 
![Screenshot 2020-09-21 at 2 20 39 PM](https://user-images.githubusercontent.com/36430592/93806347-05349180-fc17-11ea-9e65-ce1fce77d5c8.png)
To Reproduce

Open Dev App on iOS
Change the theme to dark mode,
Note the top and bottom of the app is while,

**Comment by fdoxyz** [comment]
We currently have a check in place to support this for the Night theme but not for Ten X Hacket Theme. The fix should be simple enough: Check for that class element as well.

**Comment by xarielx** [comment]
@fdoxyz that is what I thought, shouldn’t be too hard. Thank you for the prompt response!
