### ISSUE TITLE
Supported device orientation

### ISSUE THREAD

**Issue by Ceri-anne** [thepracticaldev/DEV-ios#25]
The app is currently set up to support landscape orientation but there are layout/constraint issues with each tab.

Do the constraints need amending so the app still looks good in landscape? Or should landscape be removed as a supported orientation?

Issues:
* Home scene constraints need amending to match other scenes as in landscape mode, the webview and navigation bar takes up less than half of the screen.
* In portrait, the Navigation bar obscures the top menu bar from the webview. In landscape, the navigation bar isn't deep enough to cover it. Should probably hide the top menu bar anyway if it should be hidden (as is currently done in `LoginViewController` `hideNavBar` function).

![simulator screen shot - iphone x landscape](https://user-images.githubusercontent.com/17088316/45919539-c3897880-be8e-11e8-9f0b-8fffab25c9c4.png)

**Comment by benhalpern** [comment]
I decided it was easier and more typical with this kind of app to disable orientation. This was the idea all along, just didn't get to it. Thanks for the heads up. It's been pushed.
