### ISSUE TITLE
Replace "user tab" smiley face with logged-in user's profile image

### ISSUE THREAD

**Issue by benhalpern** [thepracticaldev/DEV-ios#28]
We currently grab user's data in order to determine which logged in view to show, thanks to @Ceri-anne's great work.

The other thing we should have is the logged in user's profile image to replace the default smiley. This should be stored and served immediately when we know who the user is.

We can access the `profile_image_90` in the data we have access to. Now we just need to add it to that space in the tab bar and make it circular.

Almost ready for initial release (in fact, I'd say this is a nice-to-have, but it would be nice to have!)

**Comment by chickdan** [comment]
Forgot to reference this issue with the corresponding PR, it can be closed.
