### ISSUE TITLE
Pull-to-refresh on all main tab views (except Connect)

### ISSUE THREAD

**Issue by benhalpern** [thepracticaldev/DEV-ios#29]
All the tabs are loaded via wkwebview, and it would be nice if user could pull to refresh this view. I imagine this can't be _that_ hard, but I'm not sure how to pull it off. Open for anyone!

**Comment by arpitgogia** [comment]
Hi @benhalpern, I can implement this, however it would be great if #30 can be merged as I'm using XCode 10 as well :)

**Comment by benhalpern** [comment]
Done via web instead of native
