### ISSUE TITLE
Unable to build the app in Xcode

### ISSUE THREAD

**Issue by xvercruysse** [thepracticaldev/DEV-ios#34]
I get 2 errors while trying to build the project : 
* ```error: No account for team "xxxxxxxxxx". Add a new account in the Accounts preference pane or verify that your accounts have valid credentials. (in target 'DEV')```
* ```error: No profiles for 'DEV.DEVbendevelopment' were found: Xcode couldn't find any iOS App Development provisioning profiles matching 'DEV.DEVbendevelopment'. (in target 'DEV')```

Is the free apple developper account enough or do I need a paid one?

**Comment by chickdan** [comment]
The free account will work fine :)
