### ISSUE TITLE
Determine how to handle notification refresh/mark as read

### ISSUE THREAD

**Issue by benhalpern** [thepracticaldev/DEV-ios#37]
This may not be within the scope of just this app, but I'd like to figure this out one way or another.

Basically in the web view when the notifications page is loaded, there is a "mark as read" functionality that triggers. (A POST request to `/notifications/reads`).

I don't think it triggers in this app if the page refreshes in the background (this is correct) or if the tab is moved to (should probably mark as read in this case).

If you "refresh" the tab it does work, which makes sense, as the page is then accessed similarly to on the web.

Sorry if this doesn't make sense, it's hard to describe.

**Comment by rockarts** [comment]
Any interest in native notifications somehow hooking into the notifications @benhalpern?

**Comment by Gary-Ash** [comment]
All the notification within the app now seem to be working on actual devices

**Comment by Ceri-anne** [comment]
Is this resolved now?

**Comment by benhalpern** [comment]
Closing because out of date
