### ISSUE TITLE
Jump to proper tab in navigation

### ISSUE THREAD

**Issue by benhalpern** [thepracticaldev/DEV-ios#39]
I'm not sure how this would work exactly, but basically if we visit `/notifications` from a link in a different tab, we should jump to the notifications tab.

Somehow listening for navigation and intercepting certain paths. It might be more complicated due to the JS-driven navigation in the web app instead of full page reload.

But it could be similar to how we detect back button behavior?

Open to ideas here.

**Comment by SheldonNunes** [comment]
I am sure we can hook into the `func webView(_ webView: WKWebView, 
            didCommit navigation: WKNavigation!)` function in and inspect the intended uri for any of the tab links. 

My question would be on the intended behavior around the back button. It looks as though there is currently separate WKWebView instances for each page so would lose the history when we change the tab. 

If we did share the history between pages if someone navigates back would we expect the tab to change again?

**Comment by chickdan** [comment]
That's a good question. My first thought is it would move to a new tab, then load the page as part of that tab so there would be back button to take you back to the main page of the _current tab_. 

So say I'm in Connections, I click a link that sends me to Notifications it would move to that tab, then push to the navigation stack for the Notifications tab. If I hit the back button it would go back to the main screen for Notifications. If I tap onto the Connections tab, it will be where it left off (as if nothing happened basically). Does that make sense?

**Comment by SheldonNunes** [comment]
Yeah that makes sense.

I had a look into this and it seems like we can't leverage the WKNavigationDelegate functions (like the one I referenced) as we aren't always initiating a full page reload. We have to use Key Value Observer pattern on the url property of webview to detect all url changes. However that means we only really intercept the event after it has occurred which would mean we would have to do a navigate backwards before changing tabs. 

Seems a bit messy/hacky

Thoughts?

**Comment by jessleenyc** [comment]
Additional links we'd want this behavior for is /connect and /search and maybe /new

**Comment by SheldonNunes** [comment]
Haven't been able to find an alternative to creating an observer on the url and undoing the navigation before going to a new tab. It is fairly quick but the back icon (if not already showing) does flash before the switch :\

Any ideas/suggestions welcome!

**Comment by Gary-Ash** [comment]
Not sure if I should pose this here or but since my though could effect how navigation is implemented let me go for it. First a question...Why are we using separate views. I was going to implement adding the New Post page to a cache when I wondered why aren't we using a cache and loading a web view from it (URLCache).

**Comment by benhalpern** [comment]
Closing because out of date
