### ISSUE TITLE
Deep linking

### ISSUE THREAD

**Issue by benhalpern** [thepracticaldev/DEV-ios#40]
If I open up an article from the web, it should jump to the app in the proper page.

I know we have to add proper meta tags on the site to mark this as the official app, but I'm not so sure about the logic for opening deeper links.

I'd think most links should open in the "home" tab.

**Comment by itsdamslife** [comment]
I am working on the iOS app part of deep linking, I will commit it by end of day tomorrow.
Here are the details that are needed from webpage side the meta types.
<head>
    <meta property="al:ios:url" content="devto://news/1331" />
    <meta property="al:ios:app_store_id" content="12345678" />
    <meta property="al:ios:app_name" content="Dev.to iOS App" />
    <meta property="og:title" content="Dev.to" />
</head>

https://www.programmableweb.com/news/how-to-implement-deep-linking-ios/how-to/2015/07/14

**Comment by itsdamslife** [comment]
We can also support Universal links - https://developer.apple.com/documentation/uikit/core_app/allowing_apps_and_websites_to_link_to_your_content

**Comment by benhalpern** [comment]
Will work on universal links portion this week.

**Comment by jessleenyc** [comment]
Created this issue to add the meta info: https://github.com/thepracticaldev/dev.to/issues/1044

**Comment by jessleenyc** [comment]
Closing this issue since it seems we're all set on the iOS side based on the referenced PR
