### ISSUE TITLE
Let's ship this app to beta users

### ISSUE THREAD

**Issue by benhalpern** [thepracticaldev/DEV-ios#45]
We still have some issues to work out, but I feel like we should just get this out the door in Testflight and go from there.

If anybody is available to manage this process, we could pay a contractor to head this up for us if rates are reasonable. If anybody wants to officially help take this up either volunteer or paid, ping here or ben@dev.to.

@chickdan what do you think?

**Comment by chickdan** [comment]
Sent you an email, I'm more than happy to help out!

**Comment by StriderHND** [comment]
Sure if help need why not?

**Comment by jessleenyc** [comment]
Closing this since we got the beta app out to fewers.
