### ISSUE TITLE
User can get stuck if they don't login.

### ISSUE THREAD

**Issue by rockarts** [thepracticaldev/DEV-ios#46]
**Describe the bug**
If I don't login, click the home button and then read an article I get stuck on that article. The tab bar disappears I believe.

**To Reproduce**
Steps to reproduce the behaviour:
[GIF of Bug](https://i.imgur.com/dfXKonf.gifv)

**Expected behavior**
Tab bar should stick around for unauthenticated users.

**Comment by Ceri-anne** [comment]
Users shouldn't be able to use the app without logging in. I'll raise a PR to hide the footer on the login page :)
