### ISSUE TITLE
Missing navigation when directed to oAuth page

### ISSUE THREAD

**Issue by jessleenyc** [thepracticaldev/DEV-ios#57]
**Describe the bug**
When I click a login method (via twitter or github) I'm brought to their respective login pages, but if I change my mind (i.e. I clicked on github but want to use twitter instead), there's no way for me to navigate back to the previous page. 

**Expected behavior**
I should be able to navigate back to the DEV login page.

**Comment by Ceri-anne** [comment]
Should login be embedded in a navigation controller so you can return but only to the initial log in page? Or cancel could return the user to the app which would then send the user back to login anyway

**Comment by Ceri-anne** [comment]
Logout doesn’t sound difficult - just need to decide where it would be? Could be a button on the profile page?
