### ISSUE TITLE
Change the root view controller to point the Sign In screen when the user has not started a sessions

### ISSUE THREAD

**Issue by pablomarti** [thepracticaldev/DEV-ios#58]
When opening the app if I have not sign in it displays the bottom bar and then it changes with an ugly animation to the sign in screen.

1. Install app
2. Open the app
3. See error

What should happen is that if the user has not signed in then no loader should be displayed and it should appear immediately in the Sign In screen.

**Comment by jessleenyc** [comment]
Thanks for the issue @pablomarti. This is approved for anyone who might want to work on it.

**Comment by chickdan** [comment]
I'll be looking into this first thing tomorrow.
