### ISSUE TITLE
Navigation bar disappears when accessing to a story 

### ISSUE THREAD

**Issue by pablomarti** [thepracticaldev/DEV-ios#59]
If a not signed in user access to a story the navigation disappears.

1. Open the app
2. Scroll down and tap Home button
3. Access story

**Expected behavior**
The navigation bar should always be present when accessing a story.

![img_250d1d112db7-1](https://user-images.githubusercontent.com/672530/47531708-a2d88800-d86b-11e8-8ba3-2551b094dfd8.jpeg)

**Comment by chickdan** [comment]
Could you provide steps for how you were able to navigate to the home feed without being signed in?

**Comment by pablomarti** [comment]
@chickdan thanks, I updated the description.

**Comment by chickdan** [comment]
Interesting, this should have been fixed with #48. Are you running the beta or developer build?

**Comment by pablomarti** [comment]
I downloaded the app from TestFlight so I think it is the Beta.

**Comment by benhalpern** [comment]
Ah okay. So here's the deal: The first version we put out on testflight actually did not account for that last change to the app. Subsequent versions did. Soon enough we'll have Master as the true CI hub via Fastlane.

I'll close this issue once we have the next version live on everyone's phones.

**Comment by StriderHND** [comment]
This issue is outdated needs to be closed. please confirm @benhalpern
