### ISSUE TITLE
Change how the user signs in by using the OS web browser instead of the webview

### ISSUE THREAD

**Issue by pablomarti** [thepracticaldev/DEV-ios#60]
When doing the sign in via Github or Twitter it opens a webview but inside of the app, I would love to have it outside the app in the web browser, that way I can see my data is going directly to Github or Twitter.

(I trust Dev.to :) just thinking like a normal user).

**Comment by jessleenyc** [comment]
I think this makes sense but @benhalpern will have more thoughts.

**Comment by benhalpern** [comment]
Closing because out of date
