### ISSUE TITLE
Native iOS notifications

### ISSUE THREAD

**Issue by florimondmanca** [thepracticaldev/DEV-ios#61]
Well done on releasing this first beta version! Very happy to participate.

I am submitting this issue regarding notifications — although I am quite unaware of its technical feasibility atm, and not even sure about whether this fits the scope of the beta testing.

**Is your feature request related to a problem? Please describe.**

However, I expected the app to support native notifications. For example, I still have to enter the app to see the number of notifications, and there are no alerts when a new notification is received.

![img_2193](https://user-images.githubusercontent.com/15911462/47533327-9aa43b00-d8b3-11e8-9dd8-c6598ae9b0cc.PNG)

![img_2194](https://user-images.githubusercontent.com/15911462/47533302-88c29800-d8b3-11e8-9300-398d9d132b35.jpg)

**Describe the solution you'd like**

- Display the number of notifications on the app icon
- Fire an alert when a new notification is received, with a descriptive text.
- Allow to customise these behaviors through the standard iOS notifications settings.

**Additional context**

I was testing your app through the TestFlight program. :-)

**Comment by benhalpern** [comment]
Yeah, this definitely needs to happen.

This PR is starting to address it but I think we need more research and insight. If anyone wants to check out my comments in this PR and help me out here, greatly appreciated.

https://github.com/thepracticaldev/DEV-ios/pull/53

**Comment by StriderHND** [comment]
This issue is outdated needs to be closed. please confirm @benhalpern

**Comment by florimondmanca** [comment]
@StriderHND The only item that has not yet implemented is the notification count badge. That said, now I'd actually be fine with not having one.
