### ISSUE TITLE
User Github link doesn't open

### ISSUE THREAD

**Issue by enderahmetyurt** [thepracticaldev/DEV-ios#64]
**Describe the bug**
In a comment when clicking the user Github icon, it does nothing.

**To Reproduce**
1. Go to 'A post and look a comment'
2. Click on 'Github icon which near the username if it exists'
3. Nothing happens

**Expected behavior**
Redirecting to user Github profile.

**Smartphone (please complete the following information):**
 - OS: [e.g. iOS12.0.1]
 - Version [e.g. 1]

**Comment by jessleenyc** [comment]
Thanks for flagging. There seems to be a bug with external links only working some of the time.

**Comment by benhalpern** [comment]
Closing because out of date
