### ISSUE TITLE
Opening camera crashes app

### ISSUE THREAD

**Issue by benhalpern** [thepracticaldev/DEV-ios#65]
I assume this is a permissions thing. Basically the expected behavior in the web of being able to open the camera does not work here. You _can_ select photos.

Since we're native, we could now get more clever with our use of native APIs like the camera, but I'd say we should start with just getting it to work.

**Comment by karnett** [comment]
You're missing the camera permission in Info.plist
<key>NSCameraUsageDescription</key>
<string>Allow us to scan images for blahblah.</string>

*sorry I've been missing I'll try and help out this weekend :)

**Comment by benhalpern** [comment]
Thanks Kim! @jessleenyc you may want to jump on this.

No sorrys allowed Kim. You've been awesome. And sorry, but as a Canadian, I feel a bit of ownership over the word. 🙃🇨🇦

**Comment by chickdan** [comment]
This was fixed in #78, right?

**Comment by jessleenyc** [comment]
Yes! Closing.
