### ISSUE TITLE
Embedded tweets do not open

### ISSUE THREAD

**Issue by jessleenyc** [thepracticaldev/DEV-ios#66]
**Describe the bug**
Embedded tweets do not open when tapping them. In other apps it either opens the twitter app or safari to the twitter page. 

**To Reproduce**
1. Go to https://dev.to/ben/thoughts-on-github-actions-5g1i
2. Click on the embedded tweet
3. Notice it does not open 

**Expected behavior**
Embedded tweet should open to twitter, browser, or a browser within the app.

**Comment by benhalpern** [comment]
Hmm I'm surprised this doesn't work. 🤷‍♂️
