### ISSUE TITLE
Article engagement count not consistent within the app

### ISSUE THREAD

**Issue by JuliaTorrejon** [thepracticaldev/DEV-ios#69]
**Describe the bug**
The article engagement count :heart: is not the same when seeing MY DEV FEED that when clicking on the post.

**To Reproduce**
1. Go to MY DEV FEED
2. Check the number of 'Article Engagement Count' for any of the articles
3. Open the specific article
4. Compare the number of 'Article Engagement Count'

**Expected behavior**
Article engagement count should be consistent within the app.

**Screenshots**
![image1 1](https://user-images.githubusercontent.com/29682284/47591307-08f60580-d967-11e8-8db7-a4f5a520e103.png)

![image2](https://user-images.githubusercontent.com/29682284/47591329-1dd29900-d967-11e8-899a-b3782a6ed250.png)

**Smartphone (please complete the following information):**
 - Device: [iPhone7]
 - OS: [iOS12.0.1]
 - Version [1]

**Comment by chickdan** [comment]
@benhalpern It seems like this is an issue with the site itself rather than the app, I just tested on Desktop.

**Comment by benhalpern** [comment]
So the count there represents the summary of all reactions, so it is consistent, but I could see this being confusing. And yes, as @chickdan mentioned, this is a web thing. But I'm very happy that that isn't 100% clear what's web and what's native, that's an indicator that this approach works!
 
I'd say this is a design/style issue that could be brought up in the mothership repo:

https://github.com/thepracticaldev/dev.to

So I'll close this issue in this repo for now.
