### ISSUE TITLE
Preload "New Post" page

### ISSUE THREAD

**Issue by benhalpern** [thepracticaldev/DEV-ios#71]
When I click to compose a new post, it seems like there's no good reason that page can't already be loaded and ready to go. Similar to when we tab between views. If it's already loaded than it's instantly ready to go, giving the expected native experience.

**Comment by Gary-Ash** [comment]
I read more than I post. May want to be careful what's preloaded the initial startup is kind of killer already. just a thought

**Comment by benhalpern** [comment]
It doesn’t have to be “right at startup per se”. Could be delayed.

I’d _think_ a web view in the background wouldn’t massively impact much of anything but happy to hear otherwise.

Anyway, we don’t have to prioritize this one way or another.

**Comment by benhalpern** [comment]
Closing because out of date
