### ISSUE TITLE
Footer needs hiding in Search, Notifications and Profile tabs

### ISSUE THREAD

**Issue by Ceri-anne** [thepracticaldev/DEV-ios#72]
Currently it is possible to scroll down to the web footer and then navigate the website within that tab
![07adfcd3-6a92-4dcf-8c60-ff3d462d9c39](https://user-images.githubusercontent.com/17088316/47593238-7194b080-d96e-11e8-84f9-3586df09e653.png)

**Comment by benhalpern** [comment]
Hmmmm I could see this as a feature instead of a bug. Likely _something_ needs to change. You're probably right, but definitely worth examining.

**Comment by benhalpern** [comment]
Closing because out of date
