### ISSUE TITLE
Terms and Conditions, Code of Conduct etc should be easy to find 

### ISSUE THREAD

**Issue by Ceri-anne** [thepracticaldev/DEV-ios#73]
The only place I can find this information is in the web footer. Should these be easier to find?

**Comment by chickdan** [comment]
> We should be able to handle this all on the web side of things. I'll keep the issue open until it's dealt with.

IMO a label for these types of issues would be helpful so that contributors know from the issues page.

**Comment by benhalpern** [comment]
Good call

**Comment by Ceri-anne** [comment]
The web footer is currently being hidden because it had links to other areas of the app which were then accessible without login. Could the web-side provide a different footer if the request is from the app? Or should we instead be hiding elements of the footer and leave terms and conditions in there...?

**Comment by benhalpern** [comment]
Now that I'm thinking about it, it's not obviously a web concern. As @Ceri-anne mentions it could be done a few ways.

Still adding the label for other issues. This one may be less obvious.

**Comment by jessleenyc** [comment]
Created this issue in the web repo: https://github.com/thepracticaldev/dev.to/issues/1045

**Comment by benhalpern** [comment]
Closing because out of date
