### ISSUE TITLE
Unable to unselect home feed tags after creating an account

### ISSUE THREAD

**Issue by bryanjenningz** [thepracticaldev/DEV-ios#75]
**Describe the bug**
When you create an account, you're prompted to personalize your home feed by adding tags. If you select a tag then try to unselect it, it stays selected. If you click a tag to select it, it should unselect when you click it again.

**To Reproduce**
1. Sign in through Github on a Github account that isn't registered with dev.to.
2. Click on a tag to follow that tag, then click on that tag again to unfollow that tag and it won't work.

**Expected behavior**
If you click a tag to select it, it should unselect when you click it again.

**Screenshots**
<img width="436" alt="screen shot 2018-10-26 at 6 07 04 pm" src="https://user-images.githubusercontent.com/7637655/47598019-c6becb00-d94a-11e8-93f8-4bc5842b2bfd.png">

**Smartphone (please complete the following information):**
 - Device: iPhone XR
 - OS: iOS 12.1

**Comment by jessleenyc** [comment]
Thanks for flagging @bryanjenningz!
