### ISSUE TITLE
Clicking 'Cancel' on Twitter login page presents user with homepage without being logged in

### ISSUE THREAD

**Issue by Ceri-anne** [thepracticaldev/DEV-ios#76]
**Describe the bug**
When directed to login, if the user clicks 'Cancel' they are redirected to the homepage

**To Reproduce**
1. Open app (not logged in)
2. When presented with login screen, click on 'Auth with Twitter'
3. Click on 'Cancel'
4. Click on 'Go to The DEV Community Homepage'
5. User can now browse the website
 
**Expected behavior**
Cancelling during the login stage should return the user to the initial log in page

**Screenshots**
![loginscreen](https://user-images.githubusercontent.com/17088316/47604429-b0b81580-d9f1-11e8-9654-f92e061af1b2.png)

![twitterlogin](https://user-images.githubusercontent.com/17088316/47604428-b0b81580-d9f1-11e8-8dde-683bfe74a017.png)

![returntodev](https://user-images.githubusercontent.com/17088316/47604427-b0b81580-d9f1-11e8-82db-1f5953a9523c.png)

![homepage](https://user-images.githubusercontent.com/17088316/47604426-b01f7f00-d9f1-11e8-8e37-97a5c9936f72.png)

**Smartphone:**
 - Device: Simulator iPhone X
 - OS: iOS12
 - Version: master branch

**Comment by Gary-Ash** [comment]
I've seen that. Not sure that app is getting notification of that.

**Comment by benhalpern** [comment]
Closing this issue on this note:

https://github.com/thepracticaldev/DEV-ios/issues/93

🙂
