### ISSUE TITLE
Outlook/roadmap/thoughts on iOS app. We should be able to ship a beta soon!

### ISSUE THREAD

**Issue by benhalpern** [thepracticaldev/DEV-ios#8]
It has been a wild few days since we made our big open source push in general.

I love the enthusiasm for this project and we're pretty close to a shippable app. It's just a lot of little things.

I have really been loving Swift and iOS but I'm still a newb, so at the moment I can't give a lot of great advice on how to develop some of this stuff. That being said, I'm still pretty confident from a work-management perspective, that the native shell, web view architecture is the right way to go _for now_.

## Remaining work

- This app should only be useable via logged in. I think that's easier than supporting both states. Unlike the web version, there's not a lot of reasons you'd need to be logged out of your account. The wkwebviews in the app share the session so things just seem to work once the user is logged in. I'm open to different ways of accomplishing this, observing the loaded web view's cookies or contents for clues for logged in state, and then perhaps popping up a log in cue if they are not logged in? Or something else. We can experiment with this.
- The current "notification badge" polling is pretty naive and possibly inconsistent. This could be cleaned up a bit. We can also build in the infra to push to the app and we can coordinate to make sure this works from the core repo.
- I haven't even thought of push notifications, but we use Pusher in our main app, and they have a Push notification API, makes sense to look there, eh? But we can also ship a beta without push notifications.
- The constraints are possibly off for some phone sizes. I don't exactly have a great idea of how exactly those work, but the loading icons etc. should always be in the same place, about half to two-thirds up the screen, as long as it's the same for each tab.
- We are still early in the design of this, so I can't say I have the perfect spec for everything, so feel free to consider design adjustments, just don't clutter things. Look to Twitter/Instagram/etc. for UX cues, becasue our app is sort of the same.
- Any niceties we can build in along the way are super great. Surprise me!

I'll be more involved in this starting Monday, and will start to give better feedback on the whole process. In the meantime, thanks so much!

**Comment by chickdan** [comment]
An authentication API may not be necessary, once logged in you can find the `data-pusher-key` and `data-user` items in the body of the page. As long as that holds all of the information we need it can be extracted and attached to future http requests.

When I try logging in it goes to a blank white page so I'm not 100% sure if this method will work. I haven't had a chance to debug it, yet.

**Comment by wahyusumartha** [comment]
Yes, i have the same problem too during login, that was the reason i was asking that question actually 😀

**Comment by benhalpern** [comment]
Hmmmmmmm. Logging in _works on my machine_. But I'll investigate.

The I'm understanding it is that the session is shared for the views once one is logged in. I think that really simplifies things compared to an auth API.

**Comment by benhalpern** [comment]
Most of this has now been implemented. WIll close for new roadmap in near future.
