### ISSUE TITLE
Broken onboarding flow

### ISSUE THREAD

**Issue by jessleenyc** [thepracticaldev/DEV-ios#80]
**Describe the bug**
Submitted from a testflight user:
New joiner sign up via the app didn’t save any of the interest /hashtag preferences or my bio information that I filled out a couple times. Once it saved on the initial welcome screen, It then requested it to be filled out again on each of the tab sections as if it was the first time (see attached pic). Let me know if ya need more info!

**Screenshots**
![](https://cl.ly/8c03647f98f6/download/Image%202018-10-29%20at%206.22.45%20PM.png)

**Smartphone (please complete the following information):**
Device: iPhone10,6
iOS Version: 12.0.1

**Comment by jessleenyc** [comment]
Notes from another user: 

>I just registered to dev.to using the new App. It only worked after trying the same thing three times. Furthermore, after logging in, the individual tabs get not updated automatically and all show the screen to subscribe to topics despite having completed this step.

**Comment by Ceri-anne** [comment]
What url do users get redirected to when they log in for the first time? It probably just needs adding to the login redirect list (which should probably be an enum now)
