### ISSUE TITLE
Improve Image Upload & Copy/Paste 

### ISSUE THREAD

**Issue by jessleenyc** [thepracticaldev/DEV-ios#81]
**Is your feature request related to a problem? Please describe.**
From [a comment](https://dev.to/thejessleigh/comment/6d3e) on dev.to:

>when I try to upload an image in a comment, I’m unable to actually target and then copy the resulting url. 

**Describe the solution you'd like**
>A button to automatically copy the url to your clipboard would be fantastic!

**Comment by chickdan** [comment]
I just tested this out and was able to select and copy the resulting url. Maybe the button layout could be improved on the web side of things to allow the input field to be larger and easier to select?
