### ISSUE TITLE
Proper Coding Styles and Guidelines

### ISSUE THREAD

**Issue by lawgimenez** [thepracticaldev/DEV-ios#83]
**Is your feature request related to a problem? Please describe.**
There are different coding styles, I think we should have a single guide for coding styles.

**Describe the solution you'd like**
Take a look at Google's Swift Style guidelines or LinkedIn

**Comment by jenbutongit** [comment]
How does everyone feel about a linter? Something like [SwiftLint](https://github.com/realm/SwiftLint) will lint on build but might need some config to match whichever style is picked.

**Comment by Gary-Ash** [comment]
Never used prettier (just sort of let Xcode guild me). I do like SwiftLint

**Comment by chickdan** [comment]
Agreed on using SwiftLint, I started to set it up in Fastlane but didn't get as far as displaying the results in a PR.

**Comment by jessleenyc** [comment]
Closing this since #86 was merged!
