### ISSUE TITLE
Proposal for a modified design direction

### ISSUE THREAD

**Issue by benhalpern** [thepracticaldev/DEV-ios#88]
I want to propose a design adjustment which simplifies the initial version of this app to be released.

I propose we remove the tabs and lean in on this being an even simpler shell of the mobile web. All navigation will be via the web version of the app.

I'm seeing the last 10% of the existing approach as possibly resulting in another 90% of work. And it's not that we couldn't push it through, but I could foresee it resulting in a sort of maintenance burden we are trying to avoid.

So I think we should go with a stripped down shell that simply offers the web view, with web navigation to everything needed and a bottom bar providing back/forward and other utility buttons (view URL I'm currently on? Open in Safari? Etc.)

![image from ios](https://user-images.githubusercontent.com/3102842/47870349-bcd01880-dddf-11e8-97c5-5eb0e46e0ab6.jpg)

We are web focused, we already have all needed functionality on the web. I think we should lean in on a leaner approach and ship something that will _at least work as well as the web_.

As far as native functionality, I think we should support deep linking, push notifications, and other conveniences, but mostly try to launch something as simple as possible from an implementation perspective, and I think that is what I'm describing.

I know we put in a good deal of work in the current approach, but I don't think we should fall for a sunk cost fallacy. I think we've learned a good deal about what's been difficult, what's been easy, etc.

Final thought: If we go this way, it might be plausible that React Native or Flutter would be a better approach.

**Comment by Gary-Ash** [comment]
React Native  may be all you ever need.

https://medium.com/differential/how-to-setup-push-notifications-in-react-native-ios-android-30ea0131355e

**Comment by chickdan** [comment]
Having a minimal amount of native code really makes me question whether or not Dev.to should be a PWA. Android has pretty great support for PWAs and better support is coming to iOS.

The sketch looks like the mobile version of the site but with native forward and back navigation. If that's all that's necessary it makes more sense to me to just build that onto the web app instead.

**Comment by benhalpern** [comment]
@Gary-Ash can you give a shot at implementing this in Swift?

Sorry for the runaround, but what do you think about this approach based on our learnings?

I'll look into some alternate approaches.

**Comment by Gary-Ash** [comment]
@benhalpern have tried React? If so how did it fail? I found that video demos push notification. What more do you need really? Not sure you really need a native app with any Swift or Objective C at all

**Comment by benhalpern** [comment]
@Gary-Ash If we're doing something very simple and accessing one of the more device-specific features, the webview, to do most of the work, wouldn't we be better off developing more natively?

I feel like doing something simple makes true native the appealing option.

**Comment by benhalpern** [comment]
Hmmmm @Gary-Ash so in Android land we'd probably want something different due to the hardware back button right? Or contextual? Or would that be pretty simple to manage in React Native land?

**Comment by Gary-Ash** [comment]
you can handle it easy in an Android platform specific Component.

**Comment by nhiddink** [comment]
Has using SafariServices and SFSafariViewController been discussed yet?

**Comment by Gary-Ash** [comment]
Unless I''ve misread the documentation SFSafariViewController is used when you need to support a more opened browsing (going to any website). I believe WKWebView possibly with a URLCache system is the way to go for this app if it stays with a Swift and/or Objective C route.

**Comment by Ceri-anne** [comment]
What problems are we trying to simplify by changing direction?

**Comment by benhalpern** [comment]
@Ceri-anne While trying to get the notification badge to work appropriately, I realized that the solution to get it, and similar issues, to work, were going to be either _really hacky_ or _take a while_.

I also felt like we could apply some of the wisdom from #33 in a broader way. Basically, getting certain things to work just right in native land is not necessarily worth it if the functionality could be added more smoothly along with app logic on the web.

Ever since releasing the beta, the we've encountered small, but hairy issues. I foresaw a lifetime of this:

![](http://2.bp.blogspot.com/-X6peGqFZFZ0/UcTqFQ2O21I/AAAAAAAAPi0/uRJyfIgg9uo/s1600/blindssuck.gif)

Anyway, I'm not looking to make any rash decisions, but I made this last night:

https://github.com/benhalpern/DEV-simplified-iOS-experiment

And I'm pretty happy with it so far.

**Comment by Ceri-anne** [comment]
That’s my CSS gif 😂 

I agree with starting simple and then iterating.

**Comment by benhalpern** [comment]
@chickdan Awesome. And yeah, @Ceri-anne contributions have been super insightful. Really clever and well-executed.

My biggest concerns right now are:

- Time to launch something solid and usable
- Long term success and stable iteration

I was worried that the current state, which has been brilliantly built by the community, has a few too many issues with regards to both of those points. I think if we launch the simplified version we can use it as a stable foundation to grow from.

Anyway, still open to discussion and possibly bake-offs if @Gary-Ash or others want to demonstrate alternatives. We'll make an official choice next week but definitely leaning towards building on top of the linked experiment at this point.

**Comment by Ceri-anne** [comment]
It really doesn’t feel like it’s that far off 😊Would be good to understand what is a must to fix before we could release this version

**Comment by chickdan** [comment]
I agree, it doesn't feel far off (I have a few solutions in mind for a couple bugs I'll be working on tomorrow). That said we could always launch the minimalist version but keep this repo separate and migrate back over once it's solid.

I'm not against the minimalist approach, my concern is Apple approving the app with so little native functionality because honestly I don't know how strict they are on web based apps.

**Comment by jenbutongit** [comment]
+1 @chickdan. This is from Common App Rejections: 
> Websites served in an iOS app, web content that is not formatted for iOS, and limited web interactions do not make a quality app.
I think atm there is already too much web dependent functionality like the side navs being inside a webview so it's unlikely it will pass. 

@benhalpern I've not investigated much but with the minimalist approach, is it any different to saving the website to my home screen? It looks okay doing so, all it needs is the forward/back nav as you mention.

**Comment by Gary-Ash** [comment]
I've also been concerned with using Twitter or GitHub accounts as identification. Since the app isn't an twitter client or GitHun utility

**Comment by jenbutongit** [comment]
Using other services to authenticate is usually ok, although you should ask (add to info.plist) the user if “DEV should use “GitHub” to log in” and then open a segue rather than open inside the app. This should happen for navigating to external pages too like a gh profile

**Comment by chickdan** [comment]
@jenbutongit your question about saving the app to the home screen is along the lines of my suggestion of going the route of being a PWA. I tested it and as Ben stated, you cannot log into the PWA version.

**Comment by Gary-Ash** [comment]
@jenbutongit You may be right but one client had issues with an app that wanted to use instagram

**Comment by chickdan** [comment]
In that case maybe Twitter could be cut out but Github makes sense because DEV is a community of developers. Also I feel like this is more of a discussion to be had on the web app since that is where the authentication occurs.

**Comment by jenbutongit** [comment]
this pains me to say but a RN/Flutter app would better suited, especially if you want this out sooner rather than later. (this goes for future releases too) If not, native-fying the app would make it App Store compliant and can remain relatively stable unless there are breaking API changes. 👀

**Comment by Gary-Ash** [comment]
@jenbutongit some times the truth hurts 😄 doesn't stop it from being the truth

**Comment by chickdan** [comment]
Playing Devil's advocate: how many contributors will they have to convert to an RN/Flutter app vs keeping it native? And can that conversion really happen before the kinks are worked out of the native solution? How will RN/Flutter solve the problems we have right now?

**Comment by Ceri-anne** [comment]
I don’t have any experience with RN or Flutter, but how would they solve the issues with Github/Twitter login and it essentially being web content delivered in an app?

**Comment by jenbutongit** [comment]
Did I see a post that 50% of language posts were about/tagged JavaScript? If it was RN it might find itself with more contributors. But you’re right, I am just speculating here 😅

**Comment by chickdan** [comment]
Knowing Javascript isn't the same as knowing ReactNative, but that's a digression from the topic at hand and I'm really just trying to get people to question what's best for the project instead of choosing based on their preferred framework/platform.

**Comment by jenbutongit** [comment]
@chickdan no it doesn’t, but since it’s a js framework it is not like learning an entirely new language. Also there is the side effect of ending up with a mostly functioning Android app too. And sure, there is no guarantee those do know js want to work on a RN app. (I probably wouldn’t either, to begin with anyway😛)

@Ceri-ann apologies! I wasn’t clear. There are a few things that need to be reimplemented for it to pass the App Store, like auth for example. How many features is too many before we have to rethink this current architecture? If time is an issue, is there enough of us to keep hacking a way? 

Sorry for the hijack @benhalpern! Please move us elsewhere if required 😅

**Comment by benhalpern** [comment]
Since we went live, I shifted the new code into this repo.

But we're still open to varying approaches. I'm pretty happy with how things are evolving with the current approach, and will be able to provide more guidance shortly.

PS, we launched on Product Hunt
https://www.producthunt.com/posts/dev-to-for-ios

**Comment by benhalpern** [comment]
Closing this issue because it looks like we're settling into this approach. Thanks everyone so far, we have great things coming here!
