### ISSUE TITLE
Saving an Image Crashes the App

### ISSUE THREAD

**Issue by wolfhoundjesse** [thepracticaldev/DEV-ios#90]
I tried to save an image from a comment so I could print it and pin it up in my work area. The app crashes after clicking the Save Image action.

Copy works just fine.

**Edit:** Using the TestFlight version. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by chickdan** [comment]
Most likely a missing permission, I can take a look in a few hours unless somebody else gets to it first.

**Comment by Ceri-anne** [comment]
Are you getting this happening in the Testflight version or when running the master branch?

**Comment by wolfhoundjesse** [comment]
I’m using TestFlight per the instructions in the post. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Ceri-anne** [comment]
Cool, thanks :) The crash doesn't seem to happen in master since https://github.com/thepracticaldev/DEV-ios/pull/78 was merged in but we should add a string for **NSPhotoLibraryUsageDescription** to the plist as well

**Comment by benhalpern** [comment]
Closing this issue on this note:

https://github.com/thepracticaldev/DEV-ios/issues/93

🙂
