### ISSUE TITLE
Clicking mailto links crashes the app if there is no mail app setup

### ISSUE THREAD

**Issue by Zhao-Andy** [thepracticaldev/DEV-ios#97]
**Describe the bug**
This is reported by someone via email; details are as-is.
> I did not set mail app in my phone. I clicked your email in the app "yo@dev.to" app crashed.  I think you don't control if mail app is set in the device. Then you are trying to open mail composer. It crashes because of nil reference. 

**To Reproduce**
1. Have an iPhone with no Mail app setup
2. Visit a page with a `mailto` link, like https://dev.to/contact
3. Click on the mailto link
4. App should crash

**Expected behavior**
The app should properly handle mailto links. This might be helpful in getting to a solution:
> I think you don't control if mail app is set in the device. Then you are trying to open mail composer. It crashes because of nil reference. 

**Smartphone (please complete the following information):**
 - Device: iPhone 8
 - OS: 11.4.1

**Comment by surajdubey** [comment]
I'd like to work on this issue @Zhao-Andy @benhalpern

**Comment by nebloc** [comment]
Comes down to [this line](https://github.com/thepracticaldev/DEV-ios/blob/6bef7911712803bd64421bddd426dbde284972da/DEV-Simple/ViewController.swift#L141) 

Thread 1: Fatal error: Unexpectedly found nil while unwrapping an Optional value

**Comment by benhalpern** [comment]
Resolved by #94
