### ISSUE TITLE
Add universal link functionality

### ISSUE THREAD

**Issue by benhalpern** [thepracticaldev/DEV-ios#99]
We already have the universal link mapping on the web app, so the phone knows to open the iOS app.

But currently we are not supporting the functionality where the actual page is opened.

If I click a dev.to/ben link on the web, I'll be brought to the app, but it will just show the page I had open.

I imagine that this can be handled similarly to how we're handling opening notifications on the appropriate link. It should be fairly easy to open a specific web page given that our app is only a single `wkwebview`.

**Comment by surajdubey** [comment]
I don’t like to work on this @benhalpern

**Comment by surajdubey** [comment]
I’d like to work on this @benhalpern

**Comment by benhalpern** [comment]
Hey sorry @surajdubey this wound up being pretty simple once I got to looking at it. So I'm going to close this for now. If you see any issues with the implementation, feel free to open a supplementary PR.
